ROU-4119: fix bar border-radius with high heights values
OutSystems/outsystems-ui pull request #672
Opened 2023-02-07 16:46 UTC by BenOsodrac

This PR is for fixing progressBar progress radius when the Height value is considerable high.

### Checklist

-   [ ] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

2023-02-07 18:17 UTC, JoaoFerreira-FrontEnd approved these changes

2023-02-07 18:21 UTC, JoaoFerreira-FrontEnd requested changes
This doesn't solve the problem... only reduces the chances by half.

2023-02-09 08:50 UTC, BenOsodrac commented
> This doesn't solve the problem... only reduces the chances by half.

True, but I think it's not possible to make better than this, due to the way the pattern is made. 
The value should have been an element inside the bar, not a sibling pseudo-element.

Do you have any idea?

2023-02-09 10:03 UTC, BenOsodrac commented
> This doesn't solve the problem... only reduces the chances by half.

Added new commit with your suggestion 💪

2023-02-09 10:28 UTC, JoaoFerreira-FrontEnd approved these changes

2023-02-10 09:39 UTC, joselrio approved these changes

2023-02-10 09:40 UTC, merged