ROU-4649: Fix issue on arrow navigation when a TabHeader is disabled
OutSystems/outsystems-ui pull request #867
Opened 2023-12-04 17:45 UTC by bmarcelino-fe

This PR is for fix an issue on arrow navigation when the tabs header is disabled.

### What was happening
- When Tabs pattern contains disabled tabs header inside, it's possible to reach the element disabled using the arrows left/right
![IssueTabsDisable](https://github.com/OutSystems/outsystems-ui/assets/25321845/20c2e2d7-2492-4fef-ab92-b080ee632310)

### What was done
- Add a new list of enabled items
- Review the **_handleKeypressEvent** method to use the new list of enabled elements
- Review each key behavior to lock the navigation for disabled items
![2023-12-04 17 44 34](https://github.com/OutSystems/outsystems-ui/assets/25321845/5856342f-9991-44bd-932a-81c8a7e6b929)

### Test Steps
1. Open Sample Page
2. Navigate to tabs using Tab key
3. On tabs header, use the arrows to navigate between elements
4. Expected: The disabled tabs header can't be reached or selected.

### Screenshots

(prefer animated gif)

### Checklist

-   [ ] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

2023-12-04 18:25 UTC, BenOsodrac requested changes

2023-12-04 18:25 UTC, BenOsodrac commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
typo

2023-12-04 18:25 UTC, BenOsodrac commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
typo

2023-12-04 23:46 UTC, gnbm commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					this._updateListOfEnbaledTabsHeader();
Typo in the method's name.

2023-12-05 09:50 UTC, bmarcelino-fe commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					this._updateListOfEnbaledTabsHeader();
Done

2023-12-05 09:50 UTC, bmarcelino-fe commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
Done

2023-12-05 09:50 UTC, bmarcelino-fe commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
Done

2023-12-05 10:02 UTC, gnbm commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
Sorry, but in the comment we still have _tabhs_ instead of _tabs_

2023-12-05 10:02 UTC, gnbm commented on src/scripts/OSFramework/OSUI/Pattern/Tabs/Tabs.ts
> +					// Set the target index element based on enabled tabhs header elements
Sorry, but in the comment we still have _tabhs_ instead of _tabs_

2023-12-05 11:15 UTC, BenOsodrac approved these changes

2023-12-05 21:17 UTC, joselrio approved these changes

2023-12-06 10:12 UTC, merged