ROU-4664: Prevent dom move when inside popup
OutSystems/outsystems-ui pull request #870
Opened 2023-12-06 13:51 UTC by BenOsodrac

### Checklist

-   [ ] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

2023-12-06 14:56 UTC, BenOsodrac commented
Code-smells are unrelated to changed code.

2023-12-06 16:09 UTC, OS-giulianasilva approved these changes

2023-12-06 17:42 UTC, OS-giulianasilva approved these changes

2023-12-07 10:49 UTC, joselrio requested changes

2023-12-07 10:49 UTC, joselrio commented on src/scripts/OSFramework/OSUI/Helper/Dom.ts
> +			const _popup = document.querySelector(Constants.Dot + GlobalEnum.CssClassElements.Popup);
Can't we've more than one popup? If so, we should look by the popup that's open/active, right?

2023-12-07 10:49 UTC, joselrio commented on src/scripts/OSFramework/OSUI/Pattern/Dropdown/ServerSide/DropdownServerSide.ts
> +			// Check if the dropdown is placed inside a Popu Widget
typo at "Popu"

2023-12-07 12:07 UTC, OS-giulianasilva approved these changes

2023-12-07 13:21 UTC, joselrio approved these changes

2023-12-07 13:27 UTC, merged